version: '3.8'

services:
  db:
    build: .
    container_name: teaconnect_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: TEAConnect
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
